# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative './cocoapods_pathname_workaround'

project 'LynavoDrive'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
# Use prebuilt ReactNativeDependencies xcframework (glog/folly/boost/fmt/etc.)
# instead of building from source. Required on Xcode 26 / iOS 26 SDK where
# glog 0.3.5 source build is broken (NO_THREADS / pread / mutex.h issues).
ENV['RCT_USE_RN_DEP'] = '1'

target 'LynavoDrive' do
  config = use_native_modules!
  hermes_cli_path = '${PODS_ROOT}/hermes-engine/destroot/bin/hermesc'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'SSZipArchive', '~> 2.4'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        if target.name == 'Yoga'
          header_search_paths = build_configuration.build_settings['HEADER_SEARCH_PATHS']
          header_search_paths = ['$(inherited)'] if header_search_paths.nil?
          header_search_paths = [header_search_paths] unless header_search_paths.is_a?(Array)
          header_search_paths << '$(PODS_TARGET_SRCROOT)' unless header_search_paths.include?('$(PODS_TARGET_SRCROOT)')
          build_configuration.build_settings['HEADER_SEARCH_PATHS'] = header_search_paths
        end
      end
    end

    installer.aggregate_targets
      .map(&:user_project)
      .uniq
      .each do |project|
        project.native_targets.each do |target|
          target.build_configurations.each do |build_configuration|
            build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
            build_configuration.build_settings['HERMES_CLI_PATH'] = hermes_cli_path
          end
        end
        project.save
      end
  end
end
